[packages.homebrew]
to_remove = ["licecap"]

[packages.homebrew.common]
casks = ["bitwarden", "ghostty"]
formulae = [
"awscli",
"bitwarden-cli",
"chezmoi",       # Dotfile manager
"curl",
"gemini-cli",
"git",
"glow",          # Markdown reader
"gpg",
"gron",
"jq",
"lftp",
"openssl",       # SSL/TLS cryptography
"pygments",      # Syntax highlighter  
"ripgrep",       # Search tool
"tree",
"wget",
"zsh",
]

[packages.homebrew.personal_computer]
casks = [
"zen",
"protonvpn",
"google-drive",
"marta",
"obsidian",
"raycast",
"slack",
"spotify",
"xnviewmp",
"zoom",
]
formulae = []

[packages.homebrew.dev_computer]
casks    = ["bruno", "visual-studio-code"]
formulae = ["mise", "terraform", "tflint", "ansible"]
